"""
Submission packager - bundles proposal documents into a ZIP for delivery.
"""
import zipfile
import tempfile
import os
from typing import List, Dict
from datetime import datetime


def package_submission(
    proposal_doc: str,
    compliance_doc: str,
    attachments: List[Dict] = None,
    brief_text: str = None,
) -> str:
    """
    Package proposal, compliance matrix, brief, and attachments into a ZIP.

    Args:
        proposal_doc: Path to the proposal DOCX file
        compliance_doc: Path to the compliance matrix DOCX file
        attachments: List of {"path": str, "name": str} for additional files
        brief_text: Optional submission brief text to include

    Returns:
        Path to the generated ZIP file
    """
    attachments = attachments or []
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    tmp = tempfile.NamedTemporaryFile(
        delete=False, suffix=f"_submission_{timestamp}.zip"
    )

    with zipfile.ZipFile(tmp.name, "w", zipfile.ZIP_DEFLATED) as zf:
        # Core documents
        if os.path.exists(proposal_doc):
            zf.write(proposal_doc, "01_Proposal.docx")
        if os.path.exists(compliance_doc):
            zf.write(compliance_doc, "02_Compliance_Matrix.docx")

        # Submission brief
        if brief_text:
            zf.writestr("03_Submission_Brief.txt", brief_text)

        # Additional attachments
        for i, att in enumerate(attachments, 4):
            path = att.get("path", "")
            name = att.get("name", f"attachment_{i}")
            if path and os.path.exists(path):
                zf.write(path, f"{i:02d}_{name}")

        # Add a manifest
        manifest_lines = [
            f"Submission Package - Generated {datetime.utcnow().isoformat()}",
            "=" * 60,
            "",
            "Contents:",
            "  01_Proposal.docx - Technical/Management Proposal",
            "  02_Compliance_Matrix.docx - Requirements Traceability Matrix",
        ]
        if brief_text:
            manifest_lines.append("  03_Submission_Brief.txt - Submission Summary")
        for i, att in enumerate(attachments, 4):
            manifest_lines.append(f"  {i:02d}_{att.get('name', 'attachment')} - Attachment")
        manifest_lines.append("")
        manifest_lines.append("Generated by Sturgeon AI")
        zf.writestr("00_MANIFEST.txt", "\n".join(manifest_lines))

    return tmp.name
