import MarketplacePlaceholder from "../components/MarketplacePlaceholder";

export default function DibbsPage() {
  return (
    <MarketplacePlaceholder
      name="DLA DIBBS"
      loginUrl="https://www.dibbs.bsm.dla.mil/"
      description="DIBBS is where the Defense Logistics Agency posts solicitations. Sturgeon AI will help you evaluate NSNs, quantities, and requirements quickly."
      bullets={[
        "Log into DIBBS with your DLA credentials.",
        "Search for NSNs, parts, and opportunities that fit your capabilities.",
        "Copy solicitation text and specs into Sturgeon AI.",
        "Get rapid analysis, compliance checks, and pricing guidance.",
      ]}
      comingSoon={[
        "DIBBS-oriented RFQ analysis templates.",
        "NSN pattern detection based on data you import.",
        "Production and supply risk notes generated by AI.",
      ]}
    />
  );
}
