// app/api/marketing/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { hasModuleAccess, MODULES } from '@/lib/modules'

export async function POST(request: NextRequest) {
  try {
    const supabase = createClient()

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Check if user has access to marketing automation
    const { data: profile } = await supabase
      .from('user_profiles')
      .select('subscription_tier')
      .eq('id', user.id)
      .single()

    const userPlan = profile?.subscription_tier || 'free'
    if (!hasModuleAccess(userPlan, MODULES.MARKETING_AUTOMATION)) {
      return NextResponse.json(
        { error: 'Upgrade to Professional or Enterprise for marketing automation' },
        { status: 403 }
      )
    }

    const { action, data } = await request.json()

    switch (action) {
      case 'generate_content':
        // AI-powered content generation
        return NextResponse.json({
          success: true,
          content: {
            title: 'Sample AI-Generated Post',
            body: 'This would be generated by AI based on user input',
            platforms: ['linkedin', 'twitter']
          }
        })

      case 'schedule_post':
        // Schedule social media post
        return NextResponse.json({
          success: true,
          scheduled: true,
          scheduledFor: data.scheduledTime
        })

      default:
        return NextResponse.json(
          { error: 'Invalid action' },
          { status: 400 }
        )
    }
  } catch (error) {
    console.error('Marketing API error:', error)
    return NextResponse.json(
      { error: 'Marketing automation failed' },
      { status: 500 }
    )
  }
}
